### PR TITLE
Hh.ppe.n08 ctsm5.1.dev023

### PR DESCRIPTION
**Pull request by YifanCheng**
### Description of changes
This mainly included three changes:
1) update CTSM to the updated version
2) make selected parameters spatially distributed and make sure backward compatibility
3) fix the restarting issue in hillslope hydrology

### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):

Are answers expected to change (and if so in what way)?

Any User Interface Changes (namelist or namelist defaults changes)?

Testing performed, if any:
(List what testing you did to show your changes worked as expected)
(This can be manual testing or running of the different test suites)
(Documentation on system testing is here: https://github.com/ESCOMP/ctsm/wiki/System-Testing-Guide)
(aux_clm on cheyenne for intel/gnu and izumi for intel/gnu/nag/pgi is the standard for tags on master)

**NOTE: Be sure to check your coding style against the standard
(https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines) and review
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**

### CODE REVIEW

**Comment by apcraig** [comment]
We need to test this in RASM before we merge.  We also need to understand if any changes in the "CESM" default namelist need to be merged into the NNA namelist settings.  Yifan, do you understand those details?  Are you able to test in RASM?  Do you need me to do that?  If so, just let me know if any RASM/NNA namelist need to change as part of the merge.  We'll need to add those namelist changes explicitly.

**Comment by apcraig** [comment]
I pulled these mods into a sandbox and have verified it runs with 12km and now restart exactly.  Thanks @YifanCheng!  I will run a full test suite on this code and then approve and merge if everything else seems OK.  My sandbox also has the CTSM history changes and that seems to be working too.  So I will create a PR for that as well shortly.  More soon.

**Comment by YifanCheng** [comment]
Thank you @apcraig for testing! I was about to give it a try myself but you did faster! Looking forward to hearing more about the test!

**Comment by apcraig** [comment]
Testing looks good.  The 12km NFE5 case is now restarting exactly (with hillslope on).  It looks like the results are bit-for-bit otherwise.  That surprises me a bit but is also good I think.  I will merge now and then create another PR to fix the CTSM history namelist.

**Review by apcraig — APPROVED** [review]

**Comment by apcraig** [comment]
Just for completeness, here are the test results,

PASS  ERS.w5a_a94.X.cheyenne_intel.GC.nnav05 
PASS  ERS.w5a_a94.X.cheyenne_intel.GC.nnav05.memleak
PASS  ERS.w5a_a94.X.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
PASS  ERS.w5a_a94.X.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  ERS.w5a_a94.X.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  ERS.w5a_a94.X.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
FAIL  ERS.w5a_a94.X.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
COMMENT   tput_decr = 1.79 tput_percent_decr = 11.0
PASS  ERS.f45_g37.A.cheyenne_intel.GC.nnav05 
PASS  ERS.f45_g37.A.cheyenne_intel.GC.nnav05.memleak
PASS  ERS.f45_g37.A.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
PASS  ERS.f45_g37.A.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  ERS.f45_g37.A.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  ERS.f45_g37.A.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
FAIL  ERS.f45_g37.A.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
COMMENT   tput_decr = 5.3500000 
PASS  ERS.f45_f45.F.cheyenne_intel.GC.nnav05 
PASS  ERS.f45_f45.F.cheyenne_intel.GC.nnav05.memleak
PASS  ERS.f45_f45.F.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
FAIL  ERS.f45_f45.F.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  ERS.f45_f45.F.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  ERS.f45_f45.F.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
PASS  ERS.f45_f45.F.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
PASS  ERS.f45_g37.BCN.cheyenne_intel.GC.nnav05 
PASS  ERS.f45_g37.BCN.cheyenne_intel.GC.nnav05.memleak
PASS  ERS.f45_g37.BCN.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
FAIL  ERS.f45_g37.BCN.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  ERS.f45_g37.BCN.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  ERS.f45_g37.BCN.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
FAIL  ERS.f45_g37.BCN.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
COMMENT   tput_decr = 0.5070000 tput_percent_decr = 2.39
PASS  ERS.T62_g16.G.cheyenne_intel.GC.nnav05 
PASS  ERS.T62_g16.G.cheyenne_intel.GC.nnav05.memleak
PASS  ERS.T62_g16.G.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
PASS  ERS.T62_g16.G.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  ERS.T62_g16.G.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  ERS.T62_g16.G.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
FAIL  ERS.T62_g16.G.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
COMMENT   tput_decr = 5.397 tput_percent_decr = 10.5
PASS  ERS.T62_g16.GIAF.cheyenne_intel.GC.nnav05 
PASS  ERS.T62_g16.GIAF.cheyenne_intel.GC.nnav05.memleak
PASS  ERS.T62_g16.GIAF.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
PASS  ERS.T62_g16.GIAF.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  ERS.T62_g16.GIAF.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  ERS.T62_g16.GIAF.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
FAIL  ERS.T62_g16.GIAF.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
COMMENT   tput_decr = 0.2519999 
PASS  ERS.w5a_w5a.RI.cheyenne_intel.GC.nnav05 
PASS  ERS.w5a_w5a.RI.cheyenne_intel.GC.nnav05.memleak
PASS  ERS.w5a_w5a.RI.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
FAIL  ERS.w5a_w5a.RI.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  ERS.w5a_w5a.RI.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  ERS.w5a_w5a.RI.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
PASS  ERS.w5a_w5a.RI.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
PASS  ERS.w5a_a94.RIR.cheyenne_intel.GC.nnav05 
PASS  ERS.w5a_a94.RIR.cheyenne_intel.GC.nnav05.memleak
PASS  ERS.w5a_a94.RIR.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
FAIL  ERS.w5a_a94.RIR.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  ERS.w5a_a94.RIR.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  ERS.w5a_a94.RIR.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
PASS  ERS.w5a_a94.RIR.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
PASS  ERS.w2b_a94.RIRC.cheyenne_intel.GC.nnav05 
PASS  ERS.w2b_a94.RIRC.cheyenne_intel.GC.nnav05.memleak
PASS  ERS.w2b_a94.RIRC.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
FAIL  ERS.w2b_a94.RIRC.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  ERS.w2b_a94.RIRC.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  ERS.w2b_a94.RIRC.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
PASS  ERS.w2b_a94.RIRC.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
PASS  ERS.w5a_a94.RFR.cheyenne_intel.GC.nnav05 
PASS  ERS.w5a_a94.RFR.cheyenne_intel.GC.nnav05.memleak
PASS  ERS.w5a_a94.RFR.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
FAIL  ERS.w5a_a94.RFR.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  ERS.w5a_a94.RFR.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  ERS.w5a_a94.RFR.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
FAIL  ERS.w5a_a94.RFR.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
COMMENT    tput_percent_decr = 4.25
PASS  SMS.f19_g17.NI_CLMG.cheyenne_intel.GC.nnav05 
PASS  SMS.f19_g17.NI_CLMG.cheyenne_intel.GC.nnav05.memleak
PASS  SMS.f19_g17.NI_CLMG.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
PASS  SMS.f19_g17.NI_CLMG.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  SMS.f19_g17.NI_CLMG.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  SMS.f19_g17.NI_CLMG.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
FAIL  SMS.f19_g17.NI_CLMG.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
COMMENT   tput_decr = 1.5020000 
PASS  ERS.f19_g17.NI_CLMG.cheyenne_intel.GC.nnav05 
PASS  ERS.f19_g17.NI_CLMG.cheyenne_intel.GC.nnav05.memleak
PASS  ERS.f19_g17.NI_CLMG.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
PASS  ERS.f19_g17.NI_CLMG.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  ERS.f19_g17.NI_CLMG.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  ERS.f19_g17.NI_CLMG.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
PASS  ERS.f19_g17.NI_CLMG.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
PASS  SMS.n12a_n12a.NI_CLMG.cheyenne_intel.GC.nnav05 
PASS  SMS.n12a_n12a.NI_CLMG.cheyenne_intel.GC.nnav05.memleak
PASS  SMS.n12a_n12a.NI_CLMG.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
PASS  SMS.n12a_n12a.NI_CLMG.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  SMS.n12a_n12a.NI_CLMG.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  SMS.n12a_n12a.NI_CLMG.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
FAIL  SMS.n12a_n12a.NI_CLMG.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
COMMENT   tput_decr = 1.088 tput_percent_decr = 10.7
CFAIL ERS.n12a_n12a.NI_CLMG.cheyenne_intel.GC.nnav05 
PASS  SMS.n12a_n12a.NF.cheyenne_intel.GC.nnav05 
PASS  SMS.n12a_n12a.NF.cheyenne_intel.GC.nnav05.memleak
PASS  SMS.n12a_n12a.NF.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
PASS  SMS.n12a_n12a.NF.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  SMS.n12a_n12a.NF.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  SMS.n12a_n12a.NF.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
FAIL  SMS.n12a_n12a.NF.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
COMMENT    tput_percent_decr = 5.28
PASS  ERS.n12a_n12a.NF.cheyenne_intel.GC.nnav05 
PASS  ERS.n12a_n12a.NF.cheyenne_intel.GC.nnav05.memleak
PASS  ERS.n12a_n12a.NF.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
BFAIL ERS.n12a_n12a.NF.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  SMS.n12a_n12a.NFE5.cheyenne_intel.GC.nnav05 
PASS  SMS.n12a_n12a.NFE5.cheyenne_intel.GC.nnav05.memleak
PASS  SMS.n12a_n12a.NFE5.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
PASS  SMS.n12a_n12a.NFE5.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  SMS.n12a_n12a.NFE5.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  SMS.n12a_n12a.NFE5.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
FAIL  SMS.n12a_n12a.NFE5.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
COMMENT    tput_percent_decr = 4.39
PASS  ERS.n12a_n12a.NFE5.cheyenne_intel.GC.nnav05 
PASS  ERS.n12a_n12a.NFE5.cheyenne_intel.GC.nnav05.memleak
PASS  ERS.n12a_n12a.NFE5.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
BFAIL ERS.n12a_n12a.NFE5.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  SM2.n04a_n04a.NFE5.cheyenne_intel.GC.nnav05 
PASS  SM2.n04a_n04a.NFE5.cheyenne_intel.GC.nnav05.memleak
PASS  SM2.n04a_n04a.NFE5.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
PASS  SM2.n04a_n04a.NFE5.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  SM2.n04a_n04a.NFE5.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  SM2.n04a_n04a.NFE5.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
FAIL  SM2.n04a_n04a.NFE5.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
COMMENT    tput_percent_decr = 20.8
PASS  ER1.n04a_n04a.NFE5.cheyenne_intel.GC.nnav05 
PASS  ER1.n04a_n04a.NFE5.cheyenne_intel.GC.nnav05.memleak
PASS  ER1.n04a_n04a.NFE5.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
PASS  ER1.n04a_n04a.NFE5.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  ER1.n04a_n04a.NFE5.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  ER1.n04a_n04a.NFE5.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
FAIL  ER1.n04a_n04a.NFE5.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
COMMENT    tput_percent_decr = 15.2
PASS  SMS.w5a_w5a.NI.cheyenne_intel.GC.nnav05 
PASS  SMS.w5a_w5a.NI.cheyenne_intel.GC.nnav05.memleak
PASS  SMS.w5a_w5a.NI.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
PASS  SMS.w5a_w5a.NI.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  SMS.w5a_w5a.NI.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  SMS.w5a_w5a.NI.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
PASS  SMS.w5a_w5a.NI.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
PASS  ERS.w5a_w5a.NI.cheyenne_intel.GC.nnav05 
PASS  ERS.w5a_w5a.NI.cheyenne_intel.GC.nnav05.memleak
PASS  ERS.w5a_w5a.NI.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
PASS  ERS.w5a_w5a.NI.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  ERS.w5a_w5a.NI.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  ERS.w5a_w5a.NI.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
PASS  ERS.w5a_w5a.NI.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
PASS  SMS.w5a_a94.NIR.cheyenne_intel.GC.nnav05 
PASS  SMS.w5a_a94.NIR.cheyenne_intel.GC.nnav05.memleak
PASS  SMS.w5a_a94.NIR.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
PASS  SMS.w5a_a94.NIR.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  SMS.w5a_a94.NIR.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  SMS.w5a_a94.NIR.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
PASS  SMS.w5a_a94.NIR.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
PASS  ERS.w5a_a94.NIR.cheyenne_intel.GC.nnav05 
PASS  ERS.w5a_a94.NIR.cheyenne_intel.GC.nnav05.memleak
PASS  ERS.w5a_a94.NIR.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
FAIL  ERS.w5a_a94.NIR.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
PASS  ERS.w5a_a94.NIR.cheyenne_intel.GC.nnav05.compare_logs.rasm.nnav02 
PASS  ERS.w5a_a94.NIR.cheyenne_intel.GC.nnav05.memcomp.rasm.nnav02 
PASS  ERS.w5a_a94.NIR.cheyenne_intel.GC.nnav05.tputcomp.rasm.nnav02 
FAIL  SMS.w5a_a94.NFR.cheyenne_intel.GC.nnav05 
BFAIL SMS.w5a_a94.NFR.cheyenne_intel.GC.nnav05.generate.rasm.nnav05 
BFAIL SMS.w5a_a94.NFR.cheyenne_intel.GC.nnav05.compare_hist.rasm.nnav02 
CFAIL ERS.w5a_a94.NFR.cheyenne_intel.GC.nnav05

**Pull request merged**
